<?php

return [
    'download_free' => 3,
    'coin' => 0,
    'upload' => 10,
    'confirm' => 'working',
    'role_user' => 'user',
    'role_admin' => 'admin',
    'en' => 'en',
    'vi' => 'vi',
    'download_free_least' => 1,
    'document_url' => 'uploads/',
    'download_free_least' => 1,
    'coin_least' => 10,
    'coin_author' => 1,
    'min_quantity' => 1,
    'max_quantity' => 10,
    'coin_value' => [
        10,
        20,
        50,
        100,
        200,
        500,
    ],
    'banned_status' => 'banned',
    'image_default' => 'images/web/avatar_default.jpg',
    'invalid' => 'invalid',
];
